version: 2
updates:
  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      # Check for updates to GitHub Actions once a week (Mondays by default)
      interval: "weekly"
  # Set update schedule for pip
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      # Check for updates to Python deps once a week (Mondays by default)
      interval: "weekly"
